version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: "dev-mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    ports: 
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "dev-phpmyadmin"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - "./phpmyadmin/sessions:/sessions"